# -*- coding: utf-8 -*-
"""aula_live_python_sexta.feira

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytc5iUTZxgeLVYySi88FXNHm73hf_9T8
"""

# Faça um código que mostre a mensagem "Olá mundo!"
print("Olá mundo!")

n1 = int(input("Digite um número: "))
n1 = print(f"O número inteiro é: {n1}")

n1 = int(input("Digite um número: "))
n2 = int(input("Digite um número: "))
soma = (n1 + n2)
print(f"O resultado final é: {soma}")

n1 = int(input("Digite sua 1° nota: "))
n2 = int(input("Digite sua 2° nota: "))
n3 = int(input("Digite sua 3° nota: "))
n4 = int(input("Digite sua 4° nota: "))
media = (n1 + n2 + n3 + n4)/4
print(f"O resultado final é: {media}")

# Entrada em metros
metros = float(input("Digite o valor em metros: "))

# Conversão
centimetros = metros * 100

# Saída
print(f"{metros} metros equivalem a {centimetros} centímetros.")

import math

raio = float(input("Digite o raio do círculo: "))
area = math.pi * (raio ** 2)
print(f"A área do círculo é: {area:.2f}")

lado = float(input("Digite o lado do quadrado: "))
area = lado ** 2
dobro_area = area * 2
print(f"A área do quadrado é: {area:.2f}")
print(f"O dobro da área é: {dobro_area:.2f}")

valor_hora = float(input("Quanto você ganha por hora? "))
horas_mes = float(input("Quantas horas você trabalhou no mês? "))
salario = valor_hora * horas_mes
print(f"Seu salário no mês é: R${salario:.2f}")

valor = float(input("Digite um valor: "))
if valor > 0:
    print("O valor é positivo.")
elif valor < 0:
    print("O valor é negativo.")
else:
    print("O valor é zero.")

letra = input("Digite 'F' para Feminino ou 'M' para Masculino: ").strip().upper()

if letra == "F":
    print("F - Feminino")
elif letra == "M":
    print("M - Masculino")
else:
    print("Sexo Inválido")