# -*- coding: utf-8 -*-
"""Aula 08/08_Jackson

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1koYAvf72R5ySAYhln_bvppUSP6xaOdFR

# Atividade

"1. Faça um CÓDIGO que mostre a mensagem \"Olá Mundo!\" na tela.\n",

"2. Faça um CÓDIGO que peça um número e então mostre a mensagem O número\n",
"informado foi [número].\n",

"3. Faça um CÓDIGO que peça dois números e imprima a soma.\n",

"4. Faça um CÓDIGO que peça as 4 notas bimestrais e mostre a média final.\n",

"5. Faça um CÓDIGO que converta metros para centímetros.\n",

"6. Faça um CÓDIGO que peça o raio de um círculo, calcule e mostre sua área.\n",

"7. Faça um CÓDIGO que calcule a área de um quadrado, em seguida mostre o dobro desta\n",
"área para o usuário.\n",

"8. Faça um CÓDIGO que pergunte quanto você ganha por hora e o número de horas\n",
"trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês.\n",

"9. Faça um CÓDIGO que peça um valor e mostre na tela se o valor é positivo ou negativo.\n",

10. Faça um CÓDIGO que verifique se uma letra digitada é \"F\" ou \"M\". Conforme a letra\n",
  "escrever: F - Feminino, M - Masculino, Sexo Inválido."
"""

print("Olá Mundo!☺☻")

num= input(("Digite um número:"))
print(f"O número informado foi {num}")

num1 = int(input("Digite um número:"))
num2 = int(input("Digite outro número:"))
print(f"A soma dos números é {num1+num2}")

num1 = int(input("Digite a primeira nota:"))
num2 = int(input("Digite a segunda nota:"))
num3 = int(input("Digite a terceira nota:"))
num4 = int(input("Digite a quarta nota:"))
print(f"A média final é {(num1+num2+num3+num4)/4}")

num1 = int(input("Digite a medida em metros:"))
print(f"A medida em centímetros é {num1*100}")

num1 = int(input("Digite o raio do círculo:"))
print(f"A área do círculo é {3.14*(num1**2)}")

num1 = int(input("Digite a medida do lado do quadrado:"))
print(f"O dobro da área do quadrado é {(num1**2)*2}")

num1= int(input("Quanto você ganha por hora?"))
num2= int(input("Quantas horas você trabalha por mês?"))
print(f"Seu salário é {num1*num2}")

num= int(input("Digite um número:"))
if num>0:
  print("O número é positivo")
else:
  print("O número é negativo")

letra= input("Digite uma letra:")
if letra=="F":
  print("F - Feminino")
elif letra=="M":
  print("M - Masculino")
else:
  print("Sexo Inválido")