# -*- coding: utf-8 -*-
"""JV ALGORITIMO 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wcw0RptOm1Kb5LkBoMqHhR5J_KWHVbK0
"""

#1. Faça um CÓDIGO que mostre a mensagem "Olá Mundo!" na tela.
#2. Faça um CÓDIGO que peça um número e então mostre a mensagem O númeroinformado foi [número].
#3. Faça um CÓDIGO que peça dois números e imprima a soma.
#4. Faça um CÓDIGO que peça as 4 notas bimestrais e mostre a média final.
#5. Faça um CÓDIGO que converta metros para centímetros.
#6. Faça um CÓDIGO que peça o raio de um círculo, calcule e mostre sua área.
##7. Faça um CÓDIGO que calcule a área de um quadrado, em seguida mostre o dobro desta
##área para o usuário.
##8. Faça um CÓDIGO que pergunte quanto você ganha por hora e o número de horas
##trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês.
#9. Faça um CÓDIGO que peça um valor e mostre na tela se o valor é positivo ou negativo.
##10. Faça um CÓDIGO que verifique se uma letra digitada é "F" ou "M". Conforme a letra
##escrever: F - Feminino, M - Masculino, Sexo Inválido.

#1. Faça um CÓDIGO que mostre a mensagem "Olá Mundo!" na tela.
print("Olá Mundo!")

#2. Faça um CÓDIGO que peça um número e então mostre a mensagem O númeroinformado foi [número].
n=int(input("digite um numero "))
print(f"o numero catalogado foi {n}")

#3. Faça um CÓDIGO que peça dois números e imprima a soma.
lok= float(input("favor digite o primeiro numero "))
lok2= float(input("digite o segundo numero "))
print(f"({lok+lok2})")

#4. Faça um CÓDIGO que peça as 4 notas bimestrais e mostre a média final.
notas = []##espaço vazio, criei minha lista
for i in range(4):
  nota = float(input(f"Digite a {i+1}ª nota: "))
  notas.append(nota)##adiciona o valor recebido a lista

##posso manipular os valores dentro das listas
##sun comando de soma de valores
##len conta quantos itens tenho dentro da lista
media = sum(notas) / len(notas)

print(f"A média final é: {media}")

#5. Faça um CÓDIGO que converta metros para centímetros.
lok= float(input("favor digite "))
print(f"{lok*100:.0f}")

#6. Faça um CÓDIGO que peça o raio de um círculo, calcule e mostre sua área.
pi = 3.14159
raio = float(input("Digite o raio do círculo: "))
m = pi * raio**2

print(f"A área do círculo é: {m:.0f}")

#7. Faça um CÓDIGO que calcule a área de um quadrado, em seguida mostre o dobro desta
#área para o usuário.

lado = float(input("digite o lado do quadrado: "))
quadrado = lado **2
x = quadrado * 2

print(f"quadrado é: {quadrado}")
print(f"O dobro é: {x}")

##8. Faça um CÓDIGO que pergunte quanto você ganha por hora e o número de horas
##trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês.
ganho= float(input("digite seu valor por hora"))
mes=float(input("digite o numero de horas totais trabalhadas no mes"))

m=ganho*mes
print(m)

#9. Faça um CÓDIGO que peça um valor e mostre na tela se o valor é positivo ou negativo.
valor=int(input("digite o numero"))
if valor > 0:
  print("positivo")
elif valor ==0:
  print ("0 é neutro")
else:
  print("negativo")

##10. Faça um CÓDIGO que verifique se uma letra digitada é "F" ou "M". Conforme a letra
##escrever: F - Feminino, M - Masculino, Sexo Inválido.
letra = input("digite a letra (F ou M): ")

if letra == "F" or letra =="f":
  print("Feminino")
elif letra == "M" or letra =="m":
  print("Masculino")
else:
  print("Sexo Inválido")